repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: check-ast
- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
  - id: black
- repo: https://github.com/asottile/blacken-docs
  rev: 1.13.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==23.3.0]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.4.0
  hooks:
  - id: pyupgrade
    args: ['--py37-plus']
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: ['--config=tox.ini']
